name: Windows 실행 파일 빌드

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v4

     - 이름: Flutter 설치
  사용: subosito/flutter-action@v2
  ~와 함께:
    플러터 버전: '안정적인'
    채널: '안정적인'


      - name: Flutter 환경 확인
        run: flutter doctor

      - name: Windows 빌드 활성화
        run: flutter config --enable-windows-desktop

      - name: 의존성 설치
        run: flutter pub get

      - name: Windows 실행 파일 빌드
        run: flutter build windows

      - name: 빌드 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build/windows/runner/Release
